apiVersion: apps/v1
kind: Deployment
metadata:
  name: springcore-deployment
  labels:
    app: springcore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springcore
  template:
    metadata:
      labels:
        app: springcore
    spec:
      containers:
      - name: springcore
        image: HOLYALEXANDER23/project1:latest
        ports:
        - containerPort: 8080
